# Taps
# https://github.com/cyberark/secretless-broker/pull/1456
tap 'cyberark/tools'
tap 'homebrew/bundle'
tap 'homebrew/cask'
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-versions'
tap 'homebrew/services'
tap 'romkatv/powerlevel10k'
tap 'heroku/brew'

# Languages
brew 'go'
brew 'pyenv'
brew 'ruby'
brew 'rust'
brew 'terraform'
brew 'nvm'

# Compression/Archiving
brew 'bzip2' 
brew 'gnu-tar' 
brew 'xz'
cask 'betterzip'

# DB
brew 'mysql-client'
brew 'pgcli'
brew 'postgresql@14'
cask 'postico'

# General
brew 'bind'
brew 'cmake'
brew 'coreutils'
brew 'curl'
brew 'enchant'
brew 'gnu-getopt' 
brew 'gnutls' 
brew 'kubernetes-cli'
brew 'mermaid-cli'
brew 'openssl@1.1' 
brew 'readline' 
brew 'rename'
brew 'wget'

# Wrangling/Navigation
brew 'findutils' 
brew 'fzf'
brew 'gawk' 
brew 'gnu-sed' 
brew 'grep'
brew 'jq'
brew 'loc'
brew 'ripgrep'
brew 'the_silver_searcher'
brew 'tldr'
brew 'tree'
brew 'xsv'

# Secret Management, Encryption, etc.
brew 'age'
brew 'gopass'
brew 'gpg'
brew 'pinentry-mac'
brew 'summon'
cask 'aws-vault'
cask 'gpg-suite'

# VCS
brew 'bfg'
brew 'git'
brew 'git-delta'
brew 'hub'
brew 'svn'

# Dotfile Management
brew 'chezmoi'
brew 'powerlevel10k'

# Benchmarking / Diagnostic
brew 'hyperfine'
brew 'pv'

# Cloud
brew 'azure-cli'
brew 'heroku'

# Quicklook Plugins
# https://github.com/sindresorhus/quick-look-plugins
cask 'apparency'
cask 'qlcolorcode'
cask 'qlimagesize'
cask 'qlmarkdown'
cask 'qlstephen'
cask 'quicklook-json'
cask 'suspicious-package'
cask 'webpquicklook'

# Terminal, IDE
brew 'tmux'
brew 'vim'
cask 'iterm2'
cask 'visual-studio-code'

# Fonts
cask 'font-meslo-for-powerline'
cask 'font-meslo-lg'
cask 'font-meslo-lg-dz'
cask 'font-meslo-lg-nerd-font'
